services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/Kernel.php'

    App\MessageHandler\PaymentProcessedHandler:
        arguments:
            $adminEmail: '%env(ADMIN_EMAIL)%'
